set(RISCV_GNU_PATH $ENV{RISCV_TOOLCHAIN})

set(CMAKE_SYSTEM_PROCESSOR riscv32)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_ABI elf)

set(TOOLCHAIN_PREFIX "${CMAKE_SYSTEM_PROCESSOR}-unknown-${CMAKE_SYSTEM_ABI}-")

set(CMAKE_AR "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}ar")
set(CMAKE_ASM "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}g++")
set(CMAKE_C_COMPILER "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}g++")
set(CMAKE_LINKER "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}ld")
set(CMAKE_OBJCOPY "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}objcopy")
set(CMAKE_OBJDUMP "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}objdump")
set(CMAKE_RANLIB "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}ranlib")
set(CMAKE_SIZE "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}size")
set(CMAKE_STRIP "${RISCV_GNU_PATH}/bin/${TOOLCHAIN_PREFIX}strip")

set(CMAKE_CXX_STANDARD 17)
set(CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)


set(CMAKE_CXX_FLAGS "")
set(CMAKE_C_FLAGS "")
set(CMAKE_EXE_LINKER_FLAGS "")

string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,--print-memory-usage") # Print memory usage
string(APPEND CMAKE_EXE_LINKER_FLAGS " -Wl,-Map=map_file.map") 

