include("${CMAKE_CURRENT_LIST_DIR}/../../../../CMakeLists.txt")

set(TEST_NAME compare_lists_equal)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    compare_lists("a;b;c" "a;b;c" RET)
    ct_assert_equal(RET 1)
endfunction()

set(TEST_NAME compare_lists_equal_different_order)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    # compare_lists sorts both sides before comparing, so order does not matter
    compare_lists("c;a;b" "a;b;c" RET)
    ct_assert_equal(RET 1)
endfunction()

set(TEST_NAME compare_lists_different_length)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    compare_lists("a;b" "a;b;c" RET)
    ct_assert_equal(RET -1)
endfunction()

set(TEST_NAME compare_lists_different_content)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    compare_lists("a;b;c" "a;b;d" RET)
    ct_assert_equal(RET -1)
endfunction()

set(TEST_NAME compare_lists_empty)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    compare_lists("" "" RET)
    ct_assert_equal(RET 1)
endfunction()

set(TEST_NAME compare_lists_one_empty)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    compare_lists("a" "" RET)
    ct_assert_equal(RET -1)
endfunction()
