function(_group_custom_items GROUP_NAME TYPE)
    cmake_parse_arguments(ARG "" "PATTERN" "LIST" ${ARGN})
    
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} passed unrecognized argument ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    
    if(ARG_PATTERN AND ARG_LIST)
        message(FATAL_ERROR "Arguments PATTERN and LIST cannot be used at the same time")
    endif()
    
    # Filter items based on PATTERN or LIST
    if(ARG_PATTERN)
        if(TYPE STREQUAL "TARGET")
            get_all_targets(all_items)
        elseif(TYPE STREQUAL "IP")
            get_all_ips(all_items)
        elseif(TYPE STREQUAL "OPTION")
            get_property(all_items GLOBAL PROPERTY SOCMAKE_OPTIONS)
        endif()
        list(FILTER all_items INCLUDE REGEX "${ARG_PATTERN}")
        set(items ${all_items})
    elseif(ARG_LIST)
        set(items ${ARG_LIST})
    else()
        message(FATAL_ERROR "Specify either PATTERN or LIST arguments")
    endif()
    
    if(NOT items)
        message(WARNING "No items found for PATTERN: ${ARG_PATTERN} or LIST: ${ARG_LIST}")
        return()
    endif()
    
    # Append the GROUP_NAME to SOCMAKE_GROUPS property of the item
    foreach(item ${items})
        if(TYPE STREQUAL "OPTION")
            set_property(GLOBAL PROPERTY SOCMAKE_${item}_SOCMAKE_GROUPS "${GROUP_NAME}")
        else()
            set_property(TARGET ${item} APPEND PROPERTY SOCMAKE_GROUPS ${GROUP_NAME})
        endif()
    endforeach()
endfunction()

function(group_custom_targets GROUP_NAME)
    _group_custom_items(${GROUP_NAME} TARGET ${ARGN})
endfunction()

function(group_custom_ips GROUP_NAME)
    _group_custom_items(${GROUP_NAME} IP ${ARGN})
endfunction()

function(group_custom_options GROUP_NAME)
    _group_custom_items(${GROUP_NAME} OPTION ${ARGN})
endfunction()

function(get_all_targets_of_group OUTVAR GROUP_NAME)
    get_all_targets(all_targets)
    set(filtered_targets)
    foreach(target ${all_targets})
        get_property(target_groups TARGET ${target} PROPERTY SOCMAKE_GROUPS)
        if(${GROUP_NAME} IN_LIST target_groups)
            list(APPEND filtered_targets ${target})
        endif()
    endforeach()
    set(${OUTVAR} ${filtered_targets} PARENT_SCOPE)
endfunction()
