function(multi_option variable docstring value default)
  set(possible_values "${value}")
  if(ARGC GREATER "3")
    list(LENGTH ARGN length)
    list(PREPEND ARGN "${value}")
    list(GET ARGN "${length}" value)
    set(possible_values "${ARGN}")
  endif()

  set(${variable} ${default} CACHE STRING "${docstring}")
  set_property(CACHE ${variable} PROPERTY STRINGS "${possible_values}")
  if(NOT ${variable})
      set(${variable} ${default})
      set(${variable} ${default} PARENT_SCOPE)
  endif()
  if(NOT "${${variable}}" IN_LIST possible_values)
    message(FATAL_ERROR "The variable \"${variable}\" has an unknown value: ${${variable}}\nPossible values are: ${possible_values}")
  endif()
endfunction()

