include("${CMAKE_CURRENT_LIST_DIR}/../../../../CMakeLists.txt")

set(TEST_NAME option_string_default)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    option_string(MY_STR_OPT "A string option" "hello")
    ct_assert_equal(MY_STR_OPT "hello")
endfunction()

set(TEST_NAME option_integer_default)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    option_integer(MY_INT_OPT "An integer option" 42)
    ct_assert_equal(MY_INT_OPT 42)
endfunction()

set(TEST_NAME option_integer_zero)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    option_integer(MY_INT_ZERO_OPT "Zero integer option" 0)
    ct_assert_equal(MY_INT_ZERO_OPT 0)
endfunction()

set(TEST_NAME option_integer_non_integer_fails)
ct_add_test(NAME ${TEST_NAME} EXPECTFAIL)
function(${${TEST_NAME}})
    option_integer(MY_INT_BAD_OPT "Should fail" "notanumber")
endfunction()

set(TEST_NAME option_enum_default)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    option_enum(MY_ENUM_OPT "An enum option" "A;B;C" "A")
    ct_assert_equal(MY_ENUM_OPT "A")
endfunction()

set(TEST_NAME option_enum_invalid_value_fails)
ct_add_test(NAME ${TEST_NAME} EXPECTFAIL)
function(${${TEST_NAME}})
    option_enum(MY_ENUM_BAD_OPT "Enum option" "X;Y;Z" "INVALID")
endfunction()

set(TEST_NAME option_boolean_default_on)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    option_boolean(MY_BOOL_ON_OPT "A boolean option" ON)
    ct_assert_equal(MY_BOOL_ON_OPT "ON")
endfunction()

set(TEST_NAME option_boolean_default_off)
ct_add_test(NAME ${TEST_NAME})
function(${${TEST_NAME}})
    option_boolean(MY_BOOL_OFF_OPT "A boolean option" OFF)
    ct_assert_equal(MY_BOOL_OFF_OPT "OFF")
endfunction()

set(TEST_NAME option_string_unknown_arg_fails)
ct_add_test(NAME ${TEST_NAME} EXPECTFAIL)
function(${${TEST_NAME}})
    option_string(MY_STR_BAD_OPT "A string option" "hello" BADARG)
endfunction()
