name: testing_workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'docs/**'

jobs:

  testing:
    if: >
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.merged != true
      )

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        generator: ["Unix Makefiles", "Ninja"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake iverilog make ninja-build g++ perl cpanminus xsltproc

          pip install jinja2~=3.1.6 peakrdl==1.5.0 rich==14.2.0

      - name: run tests
        run: |
          cmake -G "${{ matrix.generator }}" -DSOCMAKE_BUILD_TESTING=TRUE -B build .

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # PR build -> no CDash update
            cmake --build build --target check
          else
            # Push / merge build -> CDash update
            cmake --build build --target check_cdash
          fi
